[uwsgi]
master=true
processes=2
threads=2
virtualenv=/opt/venv

http=0.0.0.0:8000
chdir=/app
module=mysite.wsgi:application
vacuum=true
enable-threads=true
thunder-lock=true
harakiri=30
max-requests=5000
buffer-size=65535

daemonize=none
#pidfile=/tmp/uwsgi.pid
logto=/dev/stdout
# logto=/var/log/uwsgi/uwsgi.log
log-master=true
# log-x-forwarded-for=true
# logrotate=true
# log-backupname=/var/log/uwsgi/uwsgi-%Y-%d.log
