# Generated by Django 5.1.6 on 2026-03-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '会员', 'verbose_name_plural': '会员'},
        ),
        migrations.AlterModelOptions(
            name='memberagreement',
            options={'verbose_name': '会员同意的服务条款和隐私政策', 'verbose_name_plural': '会员同意的服务条款和隐私政策'},
        ),
        migrations.AlterModelTable(
            name='memberagreement',
            table='member_agreement',
        ),
    ]
