# Generated by Django 5.1.6 on 2026-03-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options_alter_memberagreement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='memberagreement',
            table='members_member_agreement',
        ),
    ]
